In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [20]:
da =pd.read_csv('datacenter.csv')

In [21]:
da.head()

Input Volts AC  Current in Amps  Power Factor  Input Power in Watts   \
0             230        19.130435          0.80                 5500.0   
1             230        18.782609          0.80                 5400.0   
2             230        18.608696          0.80                 5350.0   
3             230        19.608696          0.82                 5500.0   
4             230        19.478261          0.80                 5600.0   

   Output Power in Watts       Time          TP      PDR     Delay  \
0                    5000  1.422431    0.934494  16.6667  0.442727   
1                    5000  1.436155  158.102000  25.0000  8.335977   
2                    5000  1.442727    0.722793  37.5000  0.342431   
3                    5000  1.445773   79.033200  50.0000  0.009614   
4                    5000  1.571562  185.938000  41.6667  0.019232   

   Efficiency in Percentage  
0                 90.909091  
1                 92.592593  
2                 93.457944  
3                 90.909091  
4                 89.285714

In [22]:
da.drop(['Input Volts AC'],axis=1,inplace=True)

In [23]:
da

Current in Amps  Power Factor  Input Power in Watts   \
0            19.130435      0.800000            5500.000000   
1            18.782609      0.800000            5400.000000   
2            18.608696      0.800000            5350.000000   
3            19.608696      0.820000            5500.000000   
4            19.478261      0.800000            5600.000000   
5            19.130435      0.800000            5500.000000   
6            18.226087      0.800000            5240.000000   
7            19.130435      0.800000            5500.000000   
8            18.434783      0.800000            5300.000000   
9            19.130435      0.800000            5500.000000   
10           19.130435      0.800000            5500.000000   
11           18.782609      0.800000            5400.000000   
12           18.608696      0.800000            5350.000000   
13           19.608696      0.820000            5500.000000   
14           19.478261      0.800000            5600.000000   
15           19.130435      0.800000            5500.000000   
16           18.226087      0.800000            5240.000000   
17           19.130435      0.800000            5500.000000   
18           18.434783      0.800000            5300.000000   
19           19.130435      0.800000            5500.000000   
20           18.782609      0.800000            5400.000000   
21           18.608696      0.800000            5350.000000   
22           19.608696      0.820000            5500.000000   
23           19.478261      0.800000            5600.000000   
24           19.130435      0.800000            5500.000000   
25           18.226087      0.800000            5240.000000   
26           19.130435      0.800000            5500.000000   
27           18.434783      0.800000            5300.000000   
28           19.130435      0.800000            5500.000000   
29           18.782609      0.800000            5400.000000   
...                ...           ...                    ...   
13982        19.901298      0.694888            6587.103999   
13983        19.901335      0.694878            6587.213597   
13984        19.901372      0.694867            6587.323195   
13985        19.901409      0.694857            6587.432793   
13986        19.901447      0.694847            6587.542391   
13987        19.901484      0.694837            6587.651989   
13988        19.901521      0.694826            6587.761587   
13989        19.901559      0.694816            6587.871184   
13990        19.901596      0.694806            6587.980782   
13991        19.901633      0.694796            6588.090380   
13992        19.901670      0.694785            6588.199978   
13993        19.901707      0.694775            6588.309576   
13994        19.901745      0.694765            6588.419174   
13995        19.901782      0.694754            6588.528772   
13996        19.901819      0.694744            6588.638370   
13997        19.901856      0.694734            6588.747968   
13998        19.901893      0.694724            6588.857566   
13999        19.901930      0.694713            6588.967164   
14000        19.901968      0.694703            6589.076762   
14001        19.902005      0.694693            6589.186360   
14002        19.902042      0.694683            6589.295958   
14003        19.902079      0.694672            6589.405556   
14004        19.902116      0.694662            6589.515154   
14005        19.902153      0.694652            6589.624752   
14006        19.902190      0.694642            6589.734350   
14007        19.902227      0.694631            6589.843948   
14008        19.902264      0.694621            6589.953546   
14009        19.902301      0.694611            6590.063143   
14010        19.902338      0.694601            6590.172741   
14011        19.902375      0.694590            6590.282339   

       Output Power in Watts        Time          TP      PDR     Delay  \
0                        

In [24]:
x= da.iloc[:,0:8].values

In [25]:
x

array([[1.91304348e+01, 8.00000000e-01, 5.50000000e+03, ...,
        9.34494000e-01, 1.66667000e+01, 4.42727000e-01],
       [1.87826087e+01, 8.00000000e-01, 5.40000000e+03, ...,
        1.58102000e+02, 2.50000000e+01, 8.33597700e+00],
       [1.86086957e+01, 8.00000000e-01, 5.35000000e+03, ...,
        7.22793000e-01, 3.75000000e+01, 3.42431000e-01],
       ...,
       [1.99023014e+01, 6.94610844e-01, 6.59006314e+03, ...,
        4.42097000e+00, 9.83624000e+01, 6.76725000e-01],
       [1.99023384e+01, 6.94600585e-01, 6.59017274e+03, ...,
        5.45984000e+00, 9.82829000e+01, 1.09373100e+00],
       [1.99023755e+01, 6.94590326e-01, 6.59028234e+03, ...,
        1.07634000e+02, 9.82964000e+01, 6.74920000e-01]])

In [26]:
y= da.iloc[:,-1].values

In [27]:
y

array([90.90909091, 92.59259259, 93.45794393, ..., 75.87180716,
       75.87054537, 75.86928363])

In [38]:
from sklearn.model_selection import train_test_split                # previously cros_validation was used in sklearn
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=0)

In [39]:
x_test

array([[1.98953195e+01, 6.96498501e-01, 6.56989712e+03, ...,
        1.73802000e+00, 9.83616000e+01, 2.77300000e-02],
       [1.95913294e+01, 7.46326482e-01, 6.03757989e+03, ...,
        3.66001000e+01, 9.72902000e+01, 4.66455000e-01],
       [1.96881863e+01, 7.33974641e-01, 6.16953582e+03, ...,
        2.42450000e+02, 9.81402000e+01, 6.01176000e-01],
       ...,
       [1.94623826e+01, 7.60535202e-01, 5.88578673e+03, ...,
        1.20599000e+01, 9.64450000e+01, 8.39900000e-03],
       [1.95408995e+01, 7.52133078e-01, 5.97554745e+03, ...,
        3.88825000e+00, 9.77853000e+01, 5.25905000e-01],
       [1.98935616e+01, 6.96960156e-01, 6.56496521e+03, ...,
        9.11022000e+01, 9.83513000e+01, 8.57308000e-01]])

In [40]:
x_train

array([[1.84347826e+01, 8.00000000e-01, 5.30000000e+03, ...,
        8.61645000e+01, 6.33333000e+01, 1.76994000e-01],
       [1.94687544e+01, 7.59878626e-01, 5.89280100e+03, ...,
        2.62665000e+01, 9.75071000e+01, 6.12158000e-01],
       [1.98934437e+01, 6.96990933e-01, 6.56463642e+03, ...,
        7.78618000e+00, 9.83781000e+01, 8.44337000e-01],
       ...,
       [1.96632824e+01, 7.37329336e-01, 6.13369729e+03, ...,
        2.43766000e+00, 9.78556000e+01, 1.24820000e-02],
       [1.97330136e+01, 7.27542246e-01, 6.23825373e+03, ...,
        2.45931000e+00, 9.81141000e+01, 4.96182000e-01],
       [1.93188708e+01, 7.74364339e-01, 5.73804869e+03, ...,
        1.47152000e+00, 9.66749000e+01, 7.02508000e-01]])

In [41]:
y_train

array([94.33962264, 84.84929327, 76.16568048, ..., 81.51690189,
       80.15063536, 87.13763627])

In [48]:
y_test

array([76.10469248, 82.81463921, 81.04337423, ..., 84.95041072,
       83.67434187, 76.16186587])

In [49]:
from sklearn.linear_model import LinearRegression
mr=LinearRegression()


In [50]:
mr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [51]:
y_predict=mr.predict(x_test)
y_predict

array([76.1289828 , 82.81223757, 81.03334666, ..., 84.96010395,
       83.67496616, 76.18377798])

In [47]:
from sklearn.metrics import r2_score            # to find accuracy
r2_score(y_test,y_predict)

0.999994206961781